### ISSUE TITLE
Steam rollback version 18158682

### ISSUE THREAD

**Issue by tankow79** [merely04/rollback-steam#2]
Please help to roll back the Steam client with the new look to the old one
Is it possible to still use the old steam in 2023?

New steam (problematic and with errors)
![steam_–_копія_vXQ7DaFZFX](https://user-images.githubusercontent.com/59967596/228415396-74fa87b6-4dd8-411f-a279-9db6a0e3eba0.png)

Old steam (just what I need)
![Old steam](https://preview.redd.it/fnv5cc8zcqj91.png?width=640&crop=smart&auto=webp&s=72b3d7eac3ec19c6c13a8b47eef0937d4fd041a8)

**Comment by merely04** [comment]
Yes. use rollback and add `-noreactlogin` to startup steam args

**Comment by tankow79** [comment]
Thanks, it worked for me.
